; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcuv2_st7789

[common]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps =
	adafruit/Adafruit GFX Library@^1.12.0
	adafruit/Adafruit AHTX0@^2.0.5
	bblanchon/ArduinoJson@^6.21.0
build_flags =
	-Wno-unused-const-variable
	-Wno-cpp
extra_scripts = pre:scripts/patch_font.py
monitor_speed = 115200

[env:nodemcuv2_st7789]
extends = common
lib_deps =
	${common.lib_deps}
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.0
build_flags =
	${common.build_flags}
	-DDISPLAY_ST7789

[env:nodemcuv2_ili9341]
extends = common
lib_deps =
	${common.lib_deps}
	adafruit/Adafruit ILI9341@^1.6.0
build_flags =
	${common.build_flags}
	-DDISPLAY_ILI9341
